[model]
provider="Anthropic"
api_key="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"

[database]
namespace="espx" 
database="espx"
user="root"
pass="root"
#
