[package]
name = "espx-lsp-server"
version = "0.1.0"
edition = "2021"
description = "lsp server for espx"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
log.workspace = true
structured-logger.workspace = true
lsp-server.workspace = true
lsp-types.workspace = true
serde.workspace = true
serde_json.workspace = true
walkdir.workspace = true
espx-ls-util = { version = "0.1", path = "../util" }
maplit = "1.0.2"
nom = "7.1.3"

espionox = {path = "../../espionox"} 
# {version = "0.1.24"}
tokio = { version = "1.28.2", features = ["full"] }
dotenv = "0.15.0"
crossbeam-channel = "0.5.11"
uuid = "1.7.0"
reqwest = "0.11.24"
surrealdb = {version = "1.2.2", features=['kv-mem']}
once_cell = "1.19.0"
toml = "0.8.12"
thiserror = "1.0.58"
rand = "0.8.5"
futures = "0.3.30"
fastembed = "3.5.0"
